#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""游戏画面状态枚举。

每个枚举值对应一个可被识别的游戏画面/节点，``value`` 同时用作模板名与
``templates_colors/`` 像素规则里的 ``state`` 字段。新增画面识别时在此追加枚举。
"""
from enum import Enum


class GameState(Enum):
    MAIN_MENU = "main_menu"
    ZERO_SYSTEM_ENTRY = "zero_system_entry"
    CODEX_SELECT = "codex_select"
    TEAM_ENTER = "team_enter"
    BUFF_SELECT = "buff_select"
    ROOM_SELECT = "room_select"
    MAP_SCREEN = "map_screen"
    COMBAT = "combat"
    COMBAT_VICTORY = "combat_victory"
    CARD_REWARD = "card_reward"
    RESULT_NEXT = "result_next"
    EVENT_SCREEN = "event_screen"
    REST_SCREEN = "rest_screen"
    DEATH_SCREEN = "death_screen"
    EXTRACTION = "extraction"
    RETREAT = "retreat_btn"
    FATE_REWARD = "fate_reward"
    NEUTRAL_CARD_SKIP = "neutral_card_skip"
    SKIP_CONFIRM = "skip_confirm"
    REMOVE_CARD_EVENT = "remove_card_event"
    CONFIRM_OPTION = "confirm_option"
    CLOSE_VIEW = "close_view"
    CONTINUE_FORWARD = "continue_forward"
    CONFIRM_ACQUIRE = "confirm_acquire"
    SKIP_LEFTMOST = "skip_leftmost"
    CARD_REWARD_SKIP = "card_reward_skip"
    COMBAT_WITHOUT_AUTO = "combat_without_auto"
    INSPIRATION_CARD = "inspiration_card"
    CARD_CONVERT = "card_convert"
    EVENT_DICE = "event_dice"
    SELECT_CHARACTER = "select_character"
    RUN_END_REWARDS = "run_end_rewards"
    WRONG_PAGE = "wrong_page"
    DELETE_SAVE = "delete_save"
    DICE_NEXT = "dice_next"
    CODEX_SYNTH = "codex_synth"
    DREAM_CONFIRM = "dream_confirm"
    CONFIRM = "confirm"
    BUG_CLOSE = "bug_close"
    SPARKLE_EVENT = "sparkle_event"
    CODEX_COMPLETE = "codex_complete"
    CLOSE_MISTOUCH = "close_mistouch"
    CARD_DUPLICATE = "card_duplicate"
    UNEXPECTED_ROOM = "unexpected_room"
    BOSS_NODE = "boss_node"
    CODEX_OBTAIN = "codex_obtain"
    CODEX_CONFIRM = "codex_confirm"
    CHAOS_CENTER = "chaos_center"
    CONFIRM_ORANGE = "confirm_orange"
    GAME_SETTLED = "game_settled"
    CONFIRM_EXTRACT = "button_extract"
    CONFIRM_PURPLE = "button_confirm_purple"
    BOSS_ROOM = "boss_room"
    CONTINUE_ORANGE = "continue_orange"
    EVENT_SKIP = "event_skip"
    COPY_CARD_CHOICE = "copy_card_choice"
    UNKNOWN = "unknown"
